### ISSUE TITLE
CMD interface should not be case sensitive

### ISSUE THREAD

**Issue by himanshujaidka** [jungkumseok/OneOS-DSL#5]
While running the CMD interface, I found that it is the case sensitive. So according to me it's not to be a case sensitive. Like "bin" dir
is present, and if user wants to change the directory then currently user need to type the exact cd bin, and cd Bin or cd BIn will not work. @jungkumseok whats your thoughts on it?

**Comment by jungkumseok** [comment]
POSIX-compliant file systems are case-sensitive, so we follow that specification
https://pubs.opengroup.org/onlinepubs/9699919799/xrat/V4_xbd_chap04.html#tag_21_04_07
